P0C/force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <label>Mail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P1/force-app/main/default/objects/Mail__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Mails</relationshipLabel>
    <relationshipName>Mails</relationshipName>
    <type>Lookup</type>
</CustomField>

P1/force-app/main/default/objects/Mail__c/fields/DeliveryStatus__c.field-meta.xml
<CustomField>
    <fullName>DeliveryStatus__c</fullName>
    <label>DeliveryStatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IN TRANSIT</fullName>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>MISSING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

P0C/force-app/main/default/classes/PastDeliveriesController.cls
public class PastDeliveriesController
{
    public List<Mail__c> deliveredMailList { public get; private set; }
    
    public PastDeliveriesController()
    {
        deliveredMailList = new List<Mail__c>();
    }
    
	public void GetPastDeliveries()
    {
        deliveredMailList = [SELECT Name, Address__c, DeliveryStatus__c FROM Mail__c WHERE DeliveryStatus__c = 'DELIVERED'];
        
        //System.debug(deliveredMailList);
    }
}