P0C/force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <label>Mail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P1/force-app/main/default/objects/Mail__c/fields/DeliveryStatus__c.field-meta.xml
<CustomField>
    <fullName>DeliveryStatus__c</fullName>
    <label>DeliveryStatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IN TRANSIT</fullName>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>MISSING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

P0C/force-app/main/default/classes/display_shipping.cls
public class display_shipping {
    private integer off = 0;
    private boolean nextbutton{get;set;}
    public Mail__c Mailstatus{get;set;}
    public list<Mail__c> maillist{get;set;}
    public display_shipping(){
        Mailstatus = new Mail__c(deliveryStatus__c = 'missing');
    }
    public void showMail(){
        maillist = [ select id from Mail__c where deliveryStatus__c =:Mailstatus.deliveryStatus__c limit 5 OFFSET: off];
    }
    public void nextpage(){
        off+=5;
        showMail();
        if(MailList.size()<5){
            nextbutton = true;
        }
    }
}